### ISSUE TITLE
remove flake8 config from pyproject.toml

### ISSUE THREAD

**Issue by piotr-rarus** [piotr-rarus/python-template#97]
Move it to separate file:

```toml
[tool.flake8]
max-line-length = 88
include = "src"
```

Fix makefile:

```Makefile
flake8:
	poetry run flake8 src
```
